Repository OpenVentPk/ventilator-app, pull requests merged in 2020-07, with the labels that each got.

#107 Add new alarm
  src/constants/Alarms.ts
  src/logic/SerialParser.tsx
  src/utils/SerialParsingHelpers.spec.tsx
  src/utils/SerialParsingHelpers.ts
Labels: enhancement

#115 Create Release APK and attach to release on creation
  .github/workflows/release-android-app.yml
  .gitignore
Labels: enhancement

#116 Build debug APK on pushes to master
  .github/workflows/build-android.yml
Labels: enhancement

#117 Refactor SerialDataHandler
  src/App.tsx
  src/interfaces/SerialDataHandlerState.ts
  src/logic/SerialDataHandler.ts
  src/logic/useReading.tsx
Labels: enhancement, refactor

#120 Remove ios folder
  ios/Podfile
  ios/openventpkVentilatorApp-tvOS/Info.plist
  ios/openventpkVentilatorApp-tvOSTests/Info.plist
  ios/openventpkVentilatorApp.xcodeproj/project.pbxproj
  ios/openventpkVentilatorApp.xcodeproj/xcshareddata/xcschemes/openventpkVentilatorApp-tvOS.xcscheme
  ios/openventpkVentilatorApp.xcodeproj/xcshareddata/xcschemes/openventpkVentilatorApp.xcscheme
  ios/openventpkVentilatorApp/AppDelegate.h
  ios/openventpkVentilatorApp/AppDelegate.m
  ios/openventpkVentilatorApp/Base.lproj/LaunchScreen.xib
  ios/openventpkVentilatorApp/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/openventpkVentilatorApp/Images.xcassets/Contents.json
  ios/openventpkVentilatorApp/Info.plist
  ios/openventpkVentilatorApp/main.m
  ios/openventpkVentilatorAppTests/Info.plist
  ios/openventpkVentilatorAppTests/openventpkVentilatorAppTests.m
Labels: refactor

#121 Update package namespaces for app
  android/.project
  android/app/_BUCK
  android/app/build.gradle
  android/app/src/debug/java/com/openventpkventilatorapp/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/openventpkventilatorapp/MainActivity.java
  android/app/src/main/java/com/openventpkventilatorapp/MainApplication.java
  android/settings.gradle
  app.json
  package.json
Labels: refactor

#122 Remove remaining ios code
  package.json
  src/App.tsx
  src/logic/SerialDataHandler.ts
Labels: refactor

#118 Add UI for configurations screen
  src/components/ConfigSelect/index.tsx
  src/components/ConnectionsHeader/styled.ts
  src/components/Globals/ConfigMetric.ts
  src/components/UpdateButton/index.tsx
  src/components/VentSwitch/index.tsx
  src/constants/Colors.ts
  src/constants/Configurables.ts
  src/constants/FontSize.ts
  src/constants/InitialVentilatorConfiguration.ts
  src/interfaces/ConfigMetric.ts
  src/screens/ConfigurationScreen.tsx
Labels: enhancement

#124 Prevent session data deletions
  src/__mocks__/react-native-fs.js
  src/constants/AppConfig.ts
  src/logic/AppLogger.ts
  src/logic/DataLogger.ts
  src/utils/FileUtils.spec.ts
  src/utils/FileUtils.ts
Labels: enhancement

#126 Clean up config ui related files
  src/components/ConfigSelect/index.tsx
  src/constants/Colors.ts
  src/constants/Configurables.ts
  src/constants/FontSize.ts
  src/constants/InitialVentilatorConfiguration.ts
  src/screens/ConfigurationScreen.tsx
Labels: refactor
