Repository OpenVentPk/ventilator-app, pull requests merged in 2020-06, with the labels that each got.

#84 Add local log of readings
  src/constants/Alarms.ts
  src/constants/InitialReading.ts
  src/logic/DataLogger.ts
  src/logic/SerialParser.tsx
  tsconfig.json
Labels: enhancement

#87 Add units to reading headers
  src/logic/DataLogger.ts
Labels: enhancement

#88 Display measured values for FiO2 and Patient Rate
  src/screens/HomeScreen.tsx
Labels: enhancement

#89 Show blank tidal volume set point on pressure control modes
  src/components/MetricDisplay.tsx
  src/components/TidalVolumeMetricDisplay.tsx
  src/constants/InitialReading.ts
  src/screens/HomeScreen.tsx
Labels: enhancement

#90 Only snooze sound on banner interaction
  src/logic/AlarmsManager.ts
Labels: enhancement

#91 Disable snoozing of Peak Pressure Alarm
  src/logic/AlarmsManager.ts
Labels: enhancement

#97 Fix app crash when switching to Alarms Panel in Pressure Modes
  android/app/build.gradle
  src/components/TidalVolumeMetricDisplay.tsx
Labels: bug

#98 Clean up application code
  package.json
  src/components/AlarmMetricDisplay.tsx
  src/components/ConnectionsHeader/styled.ts
  src/components/DetailedAlarmMetricDisplay/styles.ts
  src/components/Graphs.tsx
  src/components/Marker.tsx
  src/components/MetricCard/index.tsx
  src/components/MetricCard/styles.ts
  src/components/MetricDisplay.tsx
  src/components/OptionButton.tsx
  src/components/ParseSerial.ts
  src/components/PressureDisplay.tsx
  src/constants/Colors.ts
  src/logic/SerialDataHandler.ts
  src/logic/SerialParser.tsx
  src/navigation/BottomTabNavigator.tsx
  src/screens/AlarmsScreen.tsx
  src/screens/HomeScreen.tsx
  yarn.lock
Labels: refactor

#99 Add 1 decimal point precision
  src/components/MetricCard/index.tsx
  src/components/MetricDisplay.tsx
  src/constants/InitialReading.ts
  src/logic/SerialParser.tsx
Labels: enhancement

#101 Update serial data parsing based on packet defintion
  docs/alarm-default-thresholds-0.1.1.pdf
  docs/serial-telemetry-packet-definition-0.5.8.pdf
  docs/serial-telemetry-packet-definition.pdf
  src/logic/SerialParser.tsx
Labels: enhancement

#104 Fix overflow of units in alarm metric displays
  src/components/MetricCard/styles.ts
Labels: bug

#105 Update alarm sound
  android/app/src/main/res/raw/ventilator_alarm.mp3
  src/logic/AlarmsManager.ts
Labels: enhancement

#106 Create multiple components for data management
  src/interfaces/SerialDataRetriever.ts
  src/logic/DataLogger.ts
  src/logic/DataOrchestrator.ts
  src/logic/DummyDataGenerator.ts
  src/logic/SerialDataHandler.ts
  src/logic/SerialParser.tsx
  src/logic/UserInterfaceUpdater.ts
  src/logic/useReading.tsx
Labels: enhancement, refactor

#108 Fix failing tests
  src/__tests__/App-test.tsx
  src/components/__tests__/__snapshots__/StyledText-test.tsx.snap
Labels: bug

#109 Revert data management refactor
  src/interfaces/SerialDataRetriever.ts
  src/logic/DataLogger.ts
  src/logic/DataOrchestrator.ts
  src/logic/DummyDataGenerator.ts
  src/logic/SerialDataHandler.ts
  src/logic/SerialParser.tsx
  src/logic/UserInterfaceUpdater.ts
  src/logic/useReading.tsx
Labels: bug

#86 Add github checks on PR to master
  .github/workflows/build-and-test.yml
  package.json
Labels: enhancement

#111 Add app logging
  index.tsx
  package.json
  src/App.tsx
  src/logic/AlarmsManager.ts
  src/logic/AppLogger.ts
  src/logic/DataLogger.ts
  src/logic/DummyDataGenerator.ts
  src/logic/SerialDataHandler.ts
  src/logic/SerialParser.tsx
  src/navigation/BottomTabNavigator.tsx
  src/screens/AlarmsScreen.tsx
  yarn.lock
Labels: enhancement

#113 Add version name to generated apks
  android/app/build.gradle
Labels: enhancement

#114 Refactor workflows
  .github/workflows/build-android.yml
  .github/workflows/test.yml
  README.md
Labels: enhancement
