Repository OpenVentPk/ventilator-app, pull requests merged in 2020-05, with the labels that each got.

#15 Split alarm metrics into rows
  sample-data/data.ts
  src/Interfaces/Parameter.ts
  src/components/DetailedAlarmMetricDisplay.tsx
  src/screens/AlarmsScreen.tsx
  src/utils/helpers.ts
Labels: enhancement

#28 Model initial ventilator configuration
  src/constants/InitialVentilatorConfiguration.ts
  src/enums/VentilationBreathingType.ts
  src/enums/VentilationControlMode.ts
  src/interfaces/Parameter.ts
  src/interfaces/SetParameter.ts
  src/interfaces/VentilatorConfiguration.ts
  src/models/IERatio.ts
  src/models/VentilationMode.ts
  src/screens/HomeScreen.tsx
Labels: enhancement

#29 refactor: remove tabs that are not needed anymore
  src/navigation/BottomTabNavigator.tsx
  src/screens/ParametersScreen.tsx
Labels: refactor

#30 Add Configurations Tab
  src/navigation/BottomTabNavigator.tsx
  src/screens/ConfigurationScreen.tsx
Labels: enhancement

#31 Add alarms banner
  package.json
  src/App.tsx
  src/components/AlarmsBanner.tsx
  src/constants/Alarms.ts
  src/interfaces/Parameter.ts
  src/logic/AlarmsManager.ts
  src/logic/DummyDataGenerator.ts
  yarn.lock
Labels: enhancement

#33 Complete initial monitoring view with small testing enhancements
  android/app/src/main/assets/sample_data.txt
  package.json
  src/components/Graphs.tsx
  src/components/MetricDisplay.tsx
  src/components/PeepPressure.tsx
  src/constants/Colors.ts
  src/constants/Constants.js
  src/img/openventpk.png
  src/logic/DummyDataGenerator.ts
  src/logic/SerialDataHandler.ts
  src/logic/SerialParser.tsx
  src/logic/useReading.tsx
  src/navigation/BottomTabNavigator.tsx
  src/screens/HomeScreen.tsx
  yarn.lock
Labels: enhancement

#34 Add logo on navigation bar
  src/img/openventpk-icon.png
  src/img/openventpk-logo-transparent.png
  src/img/transparent-logo-transparent-adjusted.png
  src/img/transparent-logo-transparent-square.png
  src/navigation/BottomTabNavigator.tsx
Labels: enhancement

#35 Add alarm parsing
  src/logic/SerialParser.tsx
Labels: enhancement

#36 Add Metric Alarm components on the alarms page
  package.json
  sample-data/data.ts
  src/components/DetailedAlarmMetricDisplay.tsx
  src/components/DetailedAlarmMetricDisplay/index.tsx
  src/components/DetailedAlarmMetricDisplay/styles.ts
  src/components/Globals/Row.ts
  src/components/MetricCard/index.tsx
  src/components/MetricCard/styles.ts
  src/screens/AlarmsScreen.tsx
  yarn.lock
Labels: enhancement

#37 Add documentation
  CONTRIBUTING.md
  README.md
  img/monitoring-screenshot.png
Labels: documentation, enhancement

#39 Clean up files relating to monitoring view
  src/components/PressureDisplay.tsx
  src/constants/InitialReading.ts
  src/logic/DummyDataGenerator.ts
  src/logic/SerialParser.tsx
  src/logic/useReading.tsx
  src/screens/HomeScreen.tsx
Labels: enhancement

#40 Refactor SerialParser and update parse algorithm
  docs/serial-telemetry-packet-definition.pdf
  src/constants/VentilationModes.ts
  src/logic/SerialParser.tsx
Labels: documentation, enhancement, refactor

#41 Convert serial data values to SetParameter interfaces
  src/components/PressureDisplay.tsx
  src/constants/InitialReading.ts
  src/logic/SerialParser.tsx
  src/screens/HomeScreen.tsx
Labels: enhancement, refactor

#42 Integrate readings into alarms
  src/components/MetricCard/index.tsx
  src/components/MetricCard/styles.ts
  src/logic/SerialParser.tsx
  src/screens/AlarmsScreen.tsx
Labels: enhancement

#43 Keep screen awake during use of app
  android/app/src/main/java/com/openventpkventilatorapp/MainApplication.java
  android/settings.gradle
  ios/Podfile
  package.json
  src/App.tsx
  yarn.lock
Labels: enhancement

#45 Minor changes to app visuals
  android/app/build.gradle
  src/components/PressureDisplay.tsx
  src/constants/InitialReading.ts
  src/logic/SerialParser.tsx
  src/logic/useReading.tsx
  src/navigation/BottomTabNavigator.tsx
  src/screens/HomeScreen.tsx
Labels: bug, enhancement

#44 Add status based alarms
  src/components/ConnectionsHeader/icons.tsx
  src/components/ConnectionsHeader/index.tsx
  src/components/ConnectionsHeader/styled.ts
  src/constants/FontSize.ts
  src/screens/AlarmsScreen.tsx
Labels: enhancement

#52 Slight changes to main display
  android/app/build.gradle
  src/components/MetricDisplay.tsx
  src/components/PressureDisplay.tsx
  src/constants/InitialReading.ts
Labels: enhancement

#53 Add alarm sound during alarm states
  android/app/src/main/assets/test_log_alarms.txt
  android/app/src/main/res/raw/alarm.mp3
  package.json
  src/logic/AlarmsManager.ts
  yarn.lock
Labels: enhancement

#54 Refactor alarms with new ones
  docs/serial-telemetry-packet-definition.pdf
  src/components/ConnectionsHeader/icons.tsx
  src/components/ConnectionsHeader/index.tsx
  src/constants/Alarms.ts
Labels: enhancement

#56 Update alarms banner style
  src/logic/AlarmsManager.ts
Labels: enhancement

#57 Update FiO2 Parameter Mechanism
  docs/alarm-default-thresholds.pdf
  docs/serial-telemetry-packet-definition.pdf
  src/components/MetricCard/index.tsx
  src/constants/InitialReading.ts
  src/interfaces/SetParameter.ts
  src/logic/SerialParser.tsx
  src/screens/HomeScreen.tsx
Labels: enhancement

#58 Update app name and logo
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/strings.xml
  app.json
Labels: enhancement

#64 Refactor colors file
  src/components/Graphs.tsx
  src/components/MetricDisplay.tsx
  src/components/PressureDisplay.tsx
  src/constants/Colors.ts
  src/navigation/BottomTabNavigator.tsx
  src/screens/HomeScreen.tsx
Labels: refactor

#66 Refactor data config
  src/constants/Constants.js
  src/constants/DataConfig.ts
  src/constants/InitialReading.ts
  src/logic/DummyDataGenerator.ts
  src/logic/SerialDataHandler.ts
  src/logic/SerialParser.tsx
  src/logic/useReading.tsx
Labels: refactor

#67 Improve graph prominence
  src/components/Graphs.tsx
  src/screens/HomeScreen.tsx
Labels: enhancement

#71 Fix sweeping trends graphs
  src/constants/InitialReading.ts
  src/logic/SerialParser.tsx
Labels: enhancement

#69 Consolidate alarms screen into same theme
  src/App.tsx
  src/components/ConnectionsHeader/styled.ts
  src/components/DetailedAlarmMetricDisplay/styles.ts
  src/components/Graphs.tsx
  src/components/MetricCard/index.tsx
  src/components/MetricCard/styles.ts
  src/components/OptionButton.tsx
  src/constants/Colors.ts
  src/screens/AlarmsScreen.tsx
  src/screens/ConfigurationScreen.tsx
  src/screens/HomeScreen.tsx
Labels: enhancement

#72 Draw all data points on graph with delayed interval
  src/constants/DataConfig.ts
  src/logic/SerialParser.tsx
  src/logic/useReading.tsx
Labels: enhancement

#73 Add markers on graph to denote breath intake
  src/components/Graphs.tsx
  src/components/Marker.tsx
  src/constants/InitialReading.ts
  src/enums/BreathingPhase.ts
  src/logic/SerialParser.tsx
  src/screens/HomeScreen.tsx
Labels: enhancement
